version: 2
updates:
  - package-ecosystem: "npm"
    directory: "apps/api-gateway/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "apps/ebay-service/"
    schedule:
      interval: "weekly"
