FROM node:20-alpine

WORKDIR /app

COPY . .

RUN yarn install --frozen-lockfile --production=false

RUN yarn nx build ebay-service

EXPOSE 4100

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost:4100/health || exit 1

CMD ["node", "apps/ebay-servicedist/apps/ebay-service/src/main.js"]