FROM node:20-alpine

WORKDIR /

COPY . .

RUN yarn install --frozen-lockfile --production=false

RUN yarn nx build api-gateway

EXPOSE 4000

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost:4000/health || exit 1

CMD ["node", "apps/api-gateway/dist/apps/api-gateway/src/main.js"]