apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app: api-gateway
data:
  NODE_ENV: production
  OTEL_SERVICE_NAME: api-gateway
  JAEGER_HOST: jaeger
  JAEGER_PORT: "6832" 