/*
 * Copyright (c) 2025 Integral-X or Integral-X affiliate company. All rights reserved.
 */
import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";
import { Product } from "../types/product.types";

@Entity({ name: "products", schema: "ebay" })
export class ProductEntity implements Omit<Product, "source"> {
  /**
   * The unique identifier for the product, generated by the database.
   */
  @PrimaryGeneratedColumn("uuid")
  id!: string;

  /**
   * The name or title of the product.
   */
  @Column()
  name!: string;

  /**
   * A detailed description of the product.
   */
  @Column()
  description!: string;

  /**
   * The price of the product.
   */
  @Column("decimal", { precision: 10, scale: 2 })
  price!: number;

  /**
   * The URL of the product's image.
   */
  @Column()
  imageUrl!: string;

  constructor(partial?: Partial<ProductEntity>) {
    Object.assign(this, partial);
  }
}
