version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  api-gateway:
    build: ../apps/api-gateway
    ports:
      - '4000:4000'
    env_file:
      - ../apps/api-gateway/.env
    depends_on:
      - ebay-service
      - amazon-service
      - walmart-service
      - kafka
      - postgres
  ebay-service:
    build: ../apps/ebay-service
    ports:
      - '4100:4100'
    env_file:
      - ../apps/ebay-service/.env
    depends_on:
      - kafka
      - postgres
  amazon-service:
    build: ../apps/amazon-service
    ports:
      - '4200:4200'
    env_file:
      - ../apps/amazon-service/.env
    depends_on:
      - kafka
      - postgres
  walmart-service:
    build: ../apps/walmart-service
    ports:
      - '4300:4300'
    env_file:
      - ../apps/walmart-service/.env
    depends_on:
      - kafka
      - postgres
  frontend:
    build: ../apps/frontend
    ports:
      - '3000:3000'
    env_file:
      - ../apps/frontend/.env
volumes:
  pgdata: 