name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pr-checks:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint all projects
        run: npx nx run-many --target=lint --all
      - name: Test all projects
        run: yarn test
      - name: Build all projects
        run: yarn build

  main-checks:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint all projects
        run: npx nx run-many --target=lint --all
      - name: Test all projects
        run: yarn test
      - name: Build all projects
        run: yarn build