name: Main Checks

on:
  push:
    branches: [main]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    needs: main-checks
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build eBay Service Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.ebay-service
          push: false
          tags: ebay-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build API Gateway Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.api-gateway
          push: false
          tags: api-gateway:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
