name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Type of release"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate changelog
        id: changelog
        run: |
          # Install conventional-changelog-cli if not present
          yarn global add conventional-changelog-cli

          # Generate changelog
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0

          # Get the latest changes for release notes
          LATEST_CHANGES=$(conventional-changelog -p angular -r 1)
          echo "LATEST_CHANGES<<EOF" >> $GITHUB_OUTPUT
          echo "$LATEST_CHANGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Determine version bump
        id: version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

          # Use the input release type
          BUMP_TYPE="${{ github.event.inputs.release-type }}"
          echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT

          # Calculate new version
          NEW_VERSION=$(npm version $BUMP_TYPE --no-git-tag-version --preid=rc | sed 's/v//')
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

          # Reset package.json changes

      - name: Create release tag
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a "v${{ steps.version.outputs.new_version }}" -m "Release v${{ steps.version.outputs.new_version }}"

      - name: Push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin "v${{ steps.version.outputs.new_version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          name: Release v${{ steps.version.outputs.new_version }}
          body: |
            ## Changes in v${{ steps.version.outputs.new_version }}

            ${{ steps.changelog.outputs.LATEST_CHANGES }}

            ## Docker Images

            - eBay Service: `ghcr.io/${{ github.repository }}/ebay-service:v${{ steps.version.outputs.new_version }}`
            - API Gateway: `ghcr.io/${{ github.repository }}/api-gateway:v${{ steps.version.outputs.new_version }}`

            ## Installation

            ```bash
            docker pull ghcr.io/${{ github.repository }}/ebay-service:v${{ steps.version.outputs.new_version }}
            docker pull ghcr.io/${{ github.repository }}/api-gateway:v${{ steps.version.outputs.new_version }}
            ```
          draft: false
          prerelease: false
